# Generated by Django 4.2.6 on 2023-10-31 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('username', models.CharField(error_messages={'unique': 'Já existe um usuário com este nome de usuário.'}, max_length=40, unique=True, verbose_name='Nome de usuário')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um usuário com este e-mail.'}, max_length=254, unique=True, verbose_name='Endereço de e-mail')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super Usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='data de entrada')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='data de alteração')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('shoulder', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ombro')),
                ('chest', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peito')),
                ('right_arm', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Braço direito')),
                ('left_arm', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Braço esquerdo')),
                ('right_forearm', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Antebraço direito')),
                ('left_forearm', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Antebraço esquerdo')),
                ('right_fist', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Punho direito')),
                ('left_fist', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Punho esquerdo')),
                ('waist', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cintura')),
                ('abdomen', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Abdômen')),
                ('hip', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Quadril')),
                ('right_thigh', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Coxa direita')),
                ('left_thigh', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Coxa esquerda')),
                ('right_calf', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Panturrilha direita')),
                ('left_calf', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Panturrilha esquerda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
                'ordering': ['-created_at'],
            },
        ),
    ]
