# Generated by Django 4.2.6 on 2023-11-03 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do treino')),
                ('description', models.TextField(verbose_name='Descrição do treino')),
                ('public', models.BooleanField(default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('difficulty', models.ForeignKey(help_text='Dificuldade do treino', on_delete=django.db.models.deletion.PROTECT, related_name='workouts', to='exercise.difficulty', verbose_name='Dificuldade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Dia da semana')),
                ('description', models.TextField(verbose_name='Descrição do treino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutdays', to='manager.workout', verbose_name='Treino')),
            ],
            options={
                'verbose_name': 'Treino do dia',
                'verbose_name_plural': 'Treinos do dia',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='DayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField(blank=True, null=True, verbose_name='Repetições')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Peso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('day_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayexercises', to='manager.workoutday', verbose_name='Lista de dias')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayexercises', to='exercise.exercise', verbose_name='Exercício')),
            ],
            options={
                'verbose_name': 'Exercício do dia',
                'verbose_name_plural': 'Exercícios do dia',
                'ordering': ['day_list', 'exercise'],
            },
        ),
    ]
