# Generated by Django 4.2.6 on 2023-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_workout_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayexercise',
            name='series',
            field=models.IntegerField(default=4, verbose_name='Séries'),
        ),
    ]
