# Generated by Django 4.2.6 on 2023-11-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', help_text='Sexo para o qual a imagem é destinada', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Apenas PNG, JPG, SVG e GIF', upload_to='media/exercise_images/', verbose_name='Imagem'),
        ),
    ]
